GET http://localhost:5000/api/ncrna/category?ncrna=hsa-miR-199a-3p&source=Serum&ex_type=exosome&type=miRNA


###
GET http://localhost:5000/api/ncrna/sample?ncrna=hsa-miR-21-5p,hsa-miR-199a-3p&sample=SRR10417160,SRR10417152&type=miRNA


###
GET http://localhost:5000/api/ncrna/ncRNA_lst?ncrna=snRNA&expv=1