GET http://localhost:5000/api/ncrna/category?ncrna=hsa-miR-199a-3p&source=Serum&ex_type=Exosomes&type=miRNA


###
GET http://localhost:5000/api/ncrna/sample?ncrna=hsa-miR-21-5p,hsa-miR-199a-3p&sample=SRR10417160,SRR10417152&type=miRNA


#ncrna list: symbol loci sample_n tissue_n
###
GET http://localhost:5000/api/ncrna/ncRNA_lst
  ?ncrna=miRNA
  &filter=let
  &sort=asc
  &page=0
  &size=10

###
GET http://localhost:5000/api/ncrna/ncrnaexp?ncrna=hsa-let-7a-3p&type=miRNA&tissues=1&ex_type=Exosomes

###
GET http://localhost:5000/api/ncrna/ncrnaexp?ncrna=hsa-mir-4292-3p&type=miRNA&tissues=1&ex_type=Microvesicles

###
GET http://localhost:5000/api/ncrna/ncrnaexp?ncrna=hsa-miR-22-3p&type=miRNA&source=1&ex_type=Microvesicles

###
GET http://localhost:5000/api/ncrna/ncrnaexp?ncrna=hsa-miR-425-5p&type=miRNA&source=1&ex_type=Microvesicles


###
GET http://localhost:5000/api/ncrnaexp?ncrna=hsa-miR-21-5p&type=miRNA&tissues=1&ex_type=Exosomes

###any combination can work
GET http://localhost:5000/api/ncrna/ncrnaexp?ncrna=hsa_rRNA_HUMRGM_1:5025:+&type=rRNA&tissues=1&ex_type=1&disease=1&source=1&material=1&condition=1

###Return all expression for scatter
GET http://localhost:5000/api/ncrna/ncrnaexp?ncrna=hsa_rRNA_HUMRGM_1:5025:+&type=rRNA&ex_type=Exosomes

###srp expression for heatmap, add the tissue selector,merge=1 means cancer with normal
GET http://localhost:5000/api/ncrna/srpheatmap?srp=SRP061240&ncrna=miRNA&type=tissues&keyword=Pancreas&merge=1

###
GET http://localhost:5000/api/ncrna/srpheatmap?srp=SRP074421&ncrna=miRNA&type=tissues&keyword=Adipose&merge=1

###
GET http://localhost:5000/api/ncrna/srpheatmap?srp=SRP223523&ncrna=miRNA&type=tissues&keyword=Lung&merge=1


###
GET http://localhost:5000/api/ncrna/srpheatmap?srp=SRP122509&ncrna=miRNA&type=tissues&keyword=Lung&merge=1

###
GET http://localhost:5000/api/ncrna/srpheatmap?srp=SRP061240&ncrna=miRNA&type=ex_type&keyword=Microvesicles&merge=0

#return the top x expressed ncRNA of each ncRNA class for samples

###
GET http://localhost:5000/api/ncrna/samrankexp?sample=SRR10417160&size=30

#retuan all expressed ncrnas in ranked order
GET http://localhost:5000/api/ncrna/samrankexp?sample=SRR10417160&all=1


# return the ranked expressed ncRNA with srp_id in the given class in the tissue_id and ev_type manners
# new add by zhangq
###
GET http://localhost:5000/api/ncrna/ncrnasrpexp?srp=DRP000998&class=snorna&page=2&size=5&type=tissue_id&keyword=Mouth

###
GET http://localhost:5000/api/ncrna/ncrnasrpexp?srp=ERP013193&class=miRNA&page=1&size=5&type=ex_type&keyword=Exosomes


# return all ncRNA
###
GET http://localhost:5000/api/ncrna/ncrnasrpexp?srp=SRP214462&page=2&size=5

###
GET http://localhost:5000/api/ncrna/ncrnasrpexp
  ?srp=SRP145491
  &class=scRNA
  &filter=
  &sort=desc
  &page=0
  &size=10


###
GET http://localhost:5000/api/ncrna/ncRNA_lst
  ?ncrna=snoRNA
  &filter=103
  &sort=desc
  &page=0
  &size=10