GET http://localhost:5000/api/ncrna/srpheatmap?srp=SRP074421&ncrna=scRNA&type=tissues&keyword=Adipose&merge=1


###
GET http://localhost:5000/api/ncrna/ncrnasrpexp?srp=SRP074421&class=scRNA&filter=&active=case_mean&sort=desc&page=0&size=10&type=tissues&keyword=Adipose


###
GET http://localhost:5000/api/anno/one/HY1

###
GET http://localhost:5000/api/ncrna/ncrnaexp?ncrna=HY1&type=scRNA&source=1&ex_type=Microvesicles