GET http://localhost:5000/api/stat/category

###
GET http://localhost:5000/api/stat/samplesexp?querys=SRR10417239,SRR10733720&ncRNA_type=miRNA&query_type=sample

###
GET http://localhost:5000/api/stat/samplesexp?querys=SRR10417239,SRR10733720&query_type=sample

###
GET http://localhost:5000/api/stat/samplesexp?querys=Serum&query_type=source

#15s
GET http://localhost:5000/api/stat/samplesexp?querys=exosome&query_type=ex_type