###
GET http://localhost:5000/api/stat/category

###
GET http://localhost:5000/api/stat/samplesexp?querys=SRR10417239,SRR10733720&ncRNA_type=miRNA&query_type=sample

###
GET http://localhost:5000/api/stat/samplesexp?querys=SRR10417239,SRR10733720&query_type=sample

GET http://localhost:5000/api/stat/samplesexp?querys=Serum&query_type=source

#15s
###
GET http://localhost:5000/api/stat/samplesexp?querys=Exosomes&query_type=ex_type

###
GET http://localhost:5000/api/stat/oa_dist?query_type=ex_type&query_item=Microvesicles

###
GET http://localhost:5000/api/stat/oa_dist?query_type=tissues&query_item=Blood

###
GET http://localhost:5000/api/stat/oa_dist?query_type=condition&query_item=Disease

###
# over all sample mapping distribution
GET http://localhost:5000/api/stat/oa_dist?query_type=Microvesicles
###
GET http://localhost:5000/api/stat/oa_dist?query_type=ex_type&query_item=Exosomes

#show sample stat (size, mapping, material and source) of exsomes-tissues-material category
#the parameter of "detail" divides the above info by material

###
GET http://localhost:5000/api/stat/samstats?ex_type=Exosomes&tissues=Brain

###
GET http://localhost:5000/api/stat/samstats?ex_type=Exosomes&tissues=Brain&detail=1

#return the sample info in srp, such as the normal and disease
###
GET http://localhost:5000/api/stat/srpstats?srp=SRP168558

