###
GET http://localhost:5000/api/stat/category

###
GET http://localhost:5000/api/stat/samplesexp?querys=SRR10417239,SRR10733720&ncRNA_type=miRNA&query_type=sample

###
GET http://localhost:5000/api/stat/samplesexp?querys=SRR10417239,SRR10733720&query_type=sample

GET http://localhost:5000/api/stat/samplesexp?querys=Serum&query_type=source

#15s
###
GET http://localhost:5000/api/stat/samplesexp?querys=Exosomes&query_type=ex_type

###
# over all sample mapping distribution (Microvesicles)
GET http://localhost:5000/api/stat/oa_dist?query_type=ex_type&query_item=Microvesicles

###
GET http://localhost:5000/api/stat/oa_dist?query_type=tissues&query_item=Blood

###
GET http://localhost:5000/api/stat/oa_dist?query_type=condition&query_item=Disease

###
# over all sample mapping distribution
GET http://localhost:5000/api/stat/oa_dist?query_type=Microvesicles
###
# over all sample mapping distribution (Exosomes)
GET http://localhost:5000/api/stat/oa_dist?query_type=ex_type&query_item=Exosomes

#show sample stat (size, mapping, material and source) of exsomes-tissues-material category
#the parameter of "detail" divides the above info by material

###

###
# get tissues
GET http://localhost:5000/api/stat/samstats?ex_type=Exosomes&tissues=Breast
###
GET http://localhost:5000/api/stat/samstats?ex_type=Microvesicles&tissues=Breast

###
GET http://localhost:5000/api/stat/samstats?ex_type=Exosomes&tissues=Brain&detail=1

#return the sample info in srp, such as the normal and disease
###
GET http://localhost:5000/api/stat/srpmapstat?srp=SRP229107


#srp_lst for sample page: tissue selection
###
GET http://localhost:5000/api/stat/Srplst?select=tissues&query=Brain

###
GET http://localhost:5000/api/stat/Srplst?select=tissues&query=Bone%20marrow

###
#srp_lst for sample page: source selection
GET http://localhost:5000/api/stat/Srplst?select=source&query=Cell%20line

###add the  tissues and disease selector
GET http://localhost:5000/api/stat/srpratiostat?srp=SRP061240&samType=Control&type=tissues&keyword=Pancreas

###
GET http://localhost:5000/api/stat/srpratiostat?srp=SRP150202&samType=Control&type=ex_type&keyword=Exosomes


#get categories for keyword
###
GET http://localhost:5000/api/stat/catekey?cate=source


###
GET http://localhost:5000/api/stat/Srplst?select=tissues&query=Adipose