export default [
  // {
  //   name: 'stat',
  //   img: 'stat.png',
  //   title: 'Statistics',
  // },
  {
    name: 'Adipose',
    img: 'Adipose.png',
    title: 'Adipose',
    select: 'tissues',
  },
  {
    name: 'Adrenal gland',
    img: 'Adrenal_gland.png',
    title: 'Adrenal gland',
    select: 'tissues',
  },
  // {
  //   name: 'Bladder',
  //   img: 'Bladder.png',
  //   title: 'Bladder',
  // },
  {
    name: 'Blood',
    img: 'Blood.png',
    title: 'Blood',
    select: 'tissues',
  },
  {
    name: 'Bone marrow',
    img: 'Bone_marrow.png',
    title: 'Bone_marrow',
    select: 'tissues',
  },
  {
    name: 'Bone',
    img: 'Bone.png',
    title: 'Bone',
    select: 'tissues',
  },
  {
    name: 'Brain',
    img: 'Brain.png',
    title: 'Brain',
    select: 'tissues',
  },
  {
    name: 'Breast',
    img: 'Breast.png',
    title: 'Breast',
    select: 'tissues',
  },
  {
    name: 'Cervix',
    img: 'Cervix.png',
    title: 'Cervix',
    select: 'tissues',
  },
  {
    name: 'Colorectum',
    img: 'Colorectum.png',
    title: 'Colorectum',
    select: 'tissues',
  },
  {
    name: 'Epididymal',
    img: 'Epididymal.png',
    title: 'Epididymal',
    select: 'tissues',
  },
  {
    name: 'Hypopharynx',
    img: 'Hypopharynx.png',
    title: 'Hypopharynx',
    select: 'tissues',
  },
  {
    name: 'Kidney',
    img: 'Kidney.png',
    title: 'Kidney',
    select: 'tissues',
  },
  {
    name: 'Lung',
    img: 'Lung.png',
    title: 'Lung',
    select: 'tissues',
  },
  {
    name: 'Lymph',
    img: 'Lymph.png',
    title: 'Lymph',
    select: 'tissues',
  },
  {
    name: 'Mouth',
    img: 'Mouth.png',
    title: 'Mouth',
    select: 'tissues',
  },
  {
    name: 'Nerve',
    img: 'Nerve.png',
    title: 'Nerve',
    select: 'tissues',
  },
  {
    name: 'Ovary',
    img: 'Ovary.png',
    title: 'Ovary',
    select: 'tissues',
  },
  {
    name: 'Pancreas',
    img: 'Pancreas.png',
    title: 'Pancreas',
    select: 'tissues',
  },
  {
    name: 'Prostate',
    img: 'Prostate.png',
    title: 'Prostate',
    select: 'tissues',
  },
  {
    name: 'Skin',
    img: 'Skin.png',
    title: 'Skin',
    select: 'tissues',
  },
  {
    name: 'Stomach',
    img: 'Stomach.png',
    title: 'Stomach',
    select: 'tissues',
  },
  {
    name: 'Tongue',
    img: 'Tongue.png',
    title: 'Tongue',
    select: 'tissues',
  },
  // {
  //   name: 'Umbilical_cord',
  //   img: 'Umbilical_cord.png',
  //   title: 'Umbilical cord',
  // },
  {
    name: 'Uterus',
    img: 'Uterus.png',
    title: 'Uterus',
    select: 'tissues',
  },
  {
    name: 'Vessel',
    img: 'Vessel.png',
    title: 'Vessel',
    select: 'tissues',
  },
];
