// Generated by https://quicktype.io

export interface MirTarget {
  mirna: null;
  confidence: Confidence;
  target: string;
  pubmedid: string;
  source: string;
  experiment: Experiment;
}

export enum Confidence {
  Predict = 'predict',
  Valid = 'valid',
}

export enum Experiment {
  Empty = '-',
  Immunoprecipitation = 'Immunoprecipitation',
  Microarrays = 'Microarrays',
}
